exports.up = function up(knex) {
  return knex.schema
    .createTable('audit_history', (table) => {
      table.bigIncrements('id').primary()
      table.string('request_protocol', 15).notNullable()
        .references('protocol').inTable('request')
        .onDelete('RESTRICT')
      table.string('action_type', 100).notNullable()
      table.text('previous_value')
      table.text('new_value')
      table.string('performed_by', 100)
      table.timestamp('occurred_at').notNullable().defaultTo(knex.fn.now())
      table.text('observation')
      table.string('change_source', 50)
      table.check("change_source IN ('system', 'manual')")
      table.boolean('immutable').notNullable().defaultTo(true)
    })
    .createTable('pending_item', (table) => {
      table.uuid('id').notNullable().primary()
      table.string('request_protocol', 15).notNullable()
        .references('protocol').inTable('request')
        .onDelete('CASCADE')
      table.text('description').notNullable()
      table.boolean('visible_to_requester').notNullable().defaultTo(false)
      table.string('status', 20).notNullable().defaultTo('open')
      table.check("status IN ('open', 'overdue', 'resolved')")
      table.string('created_by', 100)
      table.timestamp('created_at').notNullable().defaultTo(knex.fn.now())
      table.string('resolved_by', 100)
      table.timestamp('resolved_at')
      table.date('due_date')
    })
    .createTable('comment', (table) => {
      table.uuid('id').notNullable().primary()
      table.string('request_protocol', 15).notNullable()
        .references('protocol').inTable('request')
        .onDelete('CASCADE')
      table.text('content').notNullable()
      table.boolean('is_internal').notNullable().defaultTo(false)
      table.string('created_by', 100)
      table.timestamp('created_at').notNullable().defaultTo(knex.fn.now())
      table.string('updated_by', 100)
      table.timestamp('updated_at')
    })
    .createTable('attachment', (table) => {
      table.uuid('id').notNullable().primary()
      table.string('request_protocol', 15).notNullable()
        .references('protocol').inTable('request')
        .onDelete('RESTRICT')
      table.string('file_name', 500).notNullable()
      table.string('file_path', 1000).notNullable()
      table.string('content_type', 100)
      table.bigInteger('size_bytes')
      table.boolean('is_restricted').notNullable().defaultTo(false)
      table.string('uploaded_by', 100)
      table.timestamp('uploaded_at').notNullable().defaultTo(knex.fn.now())
    })
}

exports.down = function down(knex) {
  return knex.schema
    .dropTableIfExists('attachment')
    .dropTableIfExists('comment')
    .dropTableIfExists('pending_item')
    .dropTableIfExists('audit_history')
}