exports.up = function up(knex) {
  return knex.schema.createTable('request', (table) => {
    table.string('protocol', 15).notNullable().primary()
    table.uuid('requester_id').notNullable()
      .references('id').inTable('requester')
      .onDelete('RESTRICT')

    table.string('process_name', 255)
    table.string('title', 255).notNullable()
    table.string('request_type', 100)
    table.text('need_description')
    table.text('problem_or_opportunity')
    table.text('expected_result')
    table.text('justification')

    table.text('current_process_description')
    table.text('process_steps')
    table.text('systems_used')
    table.string('execution_frequency', 100)
    table.string('approximate_volume', 100)
    table.integer('people_count')
    table.string('average_execution_time', 100)
    table.string('estimated_monthly_effort', 100)
    table.boolean('has_manual_controls')
    table.text('main_risks')
    table.text('operational_impact')
    table.integer('customer_impact')
    table.date('desired_deadline')
    table.string('perceived_criticality', 50)
    table.check("perceived_criticality IN ('low', 'medium', 'high', 'critical')")

    table.boolean('has_documentation')
    table.text('similar_solution')
    table.text('dependency_on_other_areas')
    table.boolean('handles_restricted_info')
    table.text('additional_notes')

    table.integer('category_id').notNullable()
      .references('id').inTable('category')
      .onDelete('RESTRICT')
    table.integer('status_id').notNullable()
      .references('id').inTable('status')
      .onDelete('RESTRICT')
    table.integer('priority_id')
      .references('id').inTable('priority')
      .onDelete('RESTRICT')

    table.string('preliminary_complexity', 50)
    table.string('triage_result', 50)
    table.text('triage_justification')
    table.text('identified_risks')

    table.uuid('assignee_id')
      .references('id').inTable('assignee')
      .onDelete('RESTRICT')

    table.date('mapping_date')
    table.time('mapping_time')
    table.string('expected_mapping_duration', 100)
    table.string('mapping_mode', 50)
    table.check("mapping_mode IN ('in_person', 'remote', 'hybrid')")
    table.string('meeting_link', 500)
    table.string('mapping_location', 255)
    table.text('expected_participants')
    table.text('mapping_notes')
    table.string('mapping_confirmation_status', 50)
    table.check("mapping_confirmation_status IN ('confirmed', 'pending', 'completed')")
    table.text('time_preferences')
    table.uuid('mapping_assignee_id')
      .references('id').inTable('assignee')
      .onDelete('RESTRICT')

    table.text('internal_notes')
    table.text('next_steps')

    table.string('created_by', 100)
    table.timestamp('created_at').notNullable().defaultTo(knex.fn.now())
    table.string('updated_by', 100)
    table.timestamp('updated_at')
    table.timestamp('last_external_update')
    table.boolean('restricted_info_flag').notNullable().defaultTo(false)
  })
}

exports.down = function down(knex) {
  return knex.schema.dropTableIfExists('request')
}