export async function seed(knex) {
  await knex("statuses").insert([
    {
      status_id: 1,
      order_number: 1,
      name: "Solicitação enviada",
      description: "Registrada pelo solicitante",
      is_final: false,
    },
    {
      status_id: 2,
      order_number: 2,
      name: "Aguardando triagem",
      description: "Na fila para análise da equipe NEO",
      is_final: false,
    },
    {
      status_id: 3,
      order_number: 3,
      name: "Em triagem",
      description: "Sendo analisada pela equipe NEO",
      is_final: false,
    },
    {
      status_id: 4,
      order_number: 4,
      name: "Pendente de informações",
      description: "Aguardando complemento do solicitante",
      is_final: false,
    },
    {
      status_id: 5,
      order_number: 5,
      name: "Aguardando mapeamento",
      description: "Elegível, aguardando agenda de mapeamento",
      is_final: false,
    },
    {
      status_id: 6,
      order_number: 6,
      name: "Mapeamento agendado",
      description: "Reunião de levantamento marcada",
      is_final: false,
    },
    {
      status_id: 7,
      order_number: 7,
      name: "Em mapeamento",
      description: "Levantamento do processo em andamento",
      is_final: false,
    },
    {
      status_id: 8,
      order_number: 8,
      name: "Em análise de viabilidade",
      description: "Avaliação técnica, de impacto e esforço",
      is_final: false,
    },
    {
      status_id: 9,
      order_number: 9,
      name: "Elegível",
      description: "Aprovada para priorização",
      is_final: false,
    },
    {
      status_id: 10,
      order_number: 10,
      name: "Não elegível",
      description: "Rejeitada na triagem",
      is_final: true,
    },
    {
      status_id: 11,
      order_number: 11,
      name: "Priorizado",
      description: "Recebeu nível de prioridade",
      is_final: false,
    },
    {
      status_id: 12,
      order_number: 12,
      name: "Backlog",
      description: "Aguardando disponibilidade de execução",
      is_final: false,
    },
    {
      status_id: 13,
      order_number: 13,
      name: "Direcionado para outra área",
      description: "Encaminhada a outro departamento",
      is_final: true,
    },
    {
      status_id: 14,
      order_number: 14,
      name: "Em desenvolvimento",
      description: "Em execução pela equipe",
      is_final: false,
    },
    {
      status_id: 15,
      order_number: 15,
      name: "Em homologação",
      description: "Em validação com o solicitante",
      is_final: false,
    },
    {
      status_id: 16,
      order_number: 16,
      name: "Concluído",
      description: "Entregue e validado",
      is_final: true,
    },
    {
      status_id: 17,
      order_number: 17,
      name: "Cancelado",
      description: "Encerrado sem execução",
      is_final: true,
    },
  ]);
}
