// `requester_user_id` (issue #53) — vínculo opcional com a conta `users`:
// - `null` = solicitação pública (modo `PUBLIC`), dados vindos do formulário;
// - preenchido = solicitação criada por usuário autenticado (qualquer perfil).
// A coincidência de e-mail entre `requesters.corporate_email` e `users.email`
// é invariante da camada de aplicação, não do banco — os exemplos abaixo
// vinculam contas de perfis distintos sem alterar os e-mails dos seeds.
// Proposital: `created_by` e o snapshot em `requesters` mantêm os dados
// originais do formulário, mesmo quando divergem da conta vinculada.
export async function seed(knex) {
  // Idempotência parcial: remove apenas as solicitações deste lote (21–30)
  // antes de reinserir. As requests 1–20 legadas e o TRUNCATE global do 001
  // seguem o padrão histórico deste arquivo.
  await knex("requests").whereIn("request_id", [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]).del();
  await knex("requests").insert([
    {
      request_id: 1,
      protocol: "MAAT-8K3P-9X2M",
      requester_id: "550e8400-e29b-41d4-a716-446655440001",
      requester_user_id: 112, // Fabio Solicitante (perfil solicitante)
      title: "Automatizar conciliação bancária",
      request_type: "Automação",
      process_name: "Conciliação bancária mensal",
      need_description: "Processo manual com alta carga operacional hoje.",
      problem_opportunity: "Conciliação manual sujeita a erros e consumo de 40h/mês.",
      expected_result: "Conciliação automatizada com conferência eletrônica.",
      justification: "O processo consome cerca de 40 horas/mês da equipe.",
      process_description: "Equipe baixa extratos, concilia em planilha e confere item a item.",
      process_steps: "1. Baixar extratos\n2. Conciliar em planilha\n3. Conferir itens",
      systems_used: "ERP, portal bancário, planilhas Excel",
      execution_frequency: "Mensal",
      approximate_volume: "~5.000 lançamentos por mês",
      people_involved: 3,
      average_duration: "5 dias úteis",
      estimated_monthly_effort: 40,
      has_manual_controls: true,
      manual_controls_detail: "Conferência dupla assinada pelo gestor.",
      main_risks: "Divergência sem identificação, retrabalho em fechamento",
      client_impact: "Atrasos no reembolso interno e retrabalho para o Financeiro.",
      operational_impact: "Alto",
      desired_deadline: "2026-09-30",
      perceived_criticality: "Alta",
      has_process_documentation: true,
      process_documentation_detail: "Fluxo desenhado no Visio (link interno).",
      has_similar_solution: false,
      depends_on_other_areas: true,
      other_areas_detail: "Financeiro aprova os lançamentos.",
      handles_restricted_info: true,
      restricted_info_detail: "Contém dados financeiros sensíveis — sigilo.",
      additional_notes: "Planilha modelo anexa para referência.",
      category_id: 1,
      status_id: 5,
      priority_id: 3,
      preliminary_complexity: "media",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440001",
      last_technical_message:
        "Sua solicitação está em análise. Assim que houver uma atualização, entraremos em contato.",
      estimated_completion: "2026-10-18",
      meeting_scheduled_for: "2026-10-15T10:30:00-03:00",
      meeting_link: null,
      created_by: "maria.silva@empresa.com",
      created_at: "2026-07-01 09:00:00",
      updated_by: "joao.analyst@empresa.com",
      updated_at: "2026-07-08 12:00:00",
    },
    {
      request_id: 2,
      protocol: "MAAT-6N2W-8VBM",
      requester_id: "550e8400-e29b-41d4-a716-446655440002",
      title: "Criar dashboard de vendas",
      request_type: "Dashboard",
      process_name: "Relatório de vendas",
      need_description: "Necessidade de visão unificada das vendas por região.",
      problem_opportunity: "Dados espalhados em planilhas sem padrão.",
      expected_result: "Dashboard com indicadores de venda em tempo real.",
      justification: "Decisões dependem de compilação manual semanal.",
      process_description: "Compilação manual de seis planilhas de vendas.",
      process_steps: "1. Coletar planilhas\n2. Consolidar\n3. Publicar relatório",
      systems_used: "CRM, planilhas, BI atual",
      execution_frequency: "Semanal",
      approximate_volume: "6 planilhas por semana",
      people_involved: 2,
      average_duration: "3 dias úteis",
      estimated_monthly_effort: 16,
      has_manual_controls: false,
      main_risks: "Consolidação manual sujeita a erro e atraso na decisão",
      client_impact: "Decisões comerciais dependem de compilação manual.",
      operational_impact: "Médio",
      desired_deadline: "2026-10-15",
      perceived_criticality: "Média",
      category_id: 2,
      status_id: 9,
      priority_id: null,
      professional_id: "650e8400-e29b-41d4-a716-446655440003",
      screening_result: "elegivel",
      last_technical_message: null,
      estimated_completion: "2026-11-30",
      meeting_scheduled_for: null,
      meeting_link: null,
      created_by: "carlos.oliveira@empresa.com",
      created_at: "2026-07-02 10:30:00",
      updated_by: "pedro.mapper@empresa.com",
      updated_at: "2026-07-18 11:00:00",
    },
    {
      request_id: 3,
      protocol: "MAAT-2R7Q-4M1C",
      requester_id: "550e8400-e29b-41d4-a716-446655440003",
      requester_user_id: 104, // Solicitante Teste (perfil solicitante)
      title: "Analisar inadimplência por região",
      request_type: "Análise de dados",
      process_name: "Análise de inadimplência mensal",
      need_description: "Relatório de inadimplência consolidado por filial.",
      problem_opportunity: "Áreas divergem sobre os números de inadimplência.",
      expected_result: "Base analítica única com valores por região e causa.",
      justification: "Evita retrabalho de reconciliação entre áreas.",
      process_description: "Equipe cruza dados de ERP com planilhas manualmente.",
      process_steps: "1. Extrair base do ERP\n2. Cruzar com planilhas\n3. Validar divergências",
      systems_used: "ERP, planilhas, Power BI",
      execution_frequency: "Mensal",
      approximate_volume: "~12.000 registros",
      people_involved: 4,
      average_duration: "4 dias úteis",
      estimated_monthly_effort: 32,
      has_manual_controls: true,
      manual_controls_detail: "Validação dupla antes da publicação.",
      main_risks: "Divergência entre áreas e base desatualizada",
      client_impact: "Decisões de crédito baseadas em dados inconsistentes.",
      operational_impact: "Alto",
      desired_deadline: "2026-11-20",
      perceived_criticality: "Alta",
      category_id: 5,
      status_id: 1,
      priority_id: null,
      professional_id: null,
      screening_result: null,
      created_by: "ana.santos@empresa.com",
      created_at: "2026-09-01 08:40:00",
      updated_by: null,
      updated_at: null,
    },
    {
      request_id: 4,
      protocol: "MAAT-9L4F-7H8S",
      requester_id: "550e8400-e29b-41d4-a716-446655440004",
      title: "Relatório de SLA da logística",
      request_type: "Dashboard ou relatório",
      process_name: "Acompanhamento de SLA de entregas",
      need_description: "Visão semanal do SLA de entregas por transportadora.",
      problem_opportunity: "SLA acompanhado em planilhas sem tratamento de exceções.",
      expected_result: "Painel com SLA, atrasos e ocorrências por operador.",
      justification: "Permite cobrança objetiva das transportadoras.",
      process_description: "Analista consolida planilhas de cada transportadora.",
      process_steps: "1. Receber planilhas\n2. Consolidar ocorrências\n3. Reportar no comitê",
      systems_used: "TMS, planilhas",
      execution_frequency: "Semanal",
      approximate_volume: "~2.000 entregas/semana",
      people_involved: 2,
      average_duration: "2 dias úteis",
      estimated_monthly_effort: 12,
      has_manual_controls: false,
      main_risks: "Ocorrências não reportadas pelas transportadoras",
      client_impact: "Clientes impactados por atrasos não monitorados.",
      operational_impact: "Médio",
      desired_deadline: "2026-10-10",
      perceived_criticality: "Média",
      category_id: 4,
      status_id: 2,
      priority_id: null,
      professional_id: null,
      screening_result: null,
      created_by: "bruno.ferreira@empresa.com",
      created_at: "2026-08-25 14:20:00",
      updated_by: null,
      updated_at: null,
    },
    {
      request_id: 5,
      protocol: "MAAT-5T2E-3P6N",
      requester_id: "550e8400-e29b-41d4-a716-446655440005",
      title: "Indicador de turnover",
      request_type: "Indicador",
      process_name: "Cálculo de turnover mensal",
      need_description: "Indicador de turnover padronizado por área.",
      problem_opportunity: "Turnover calculado de formas diferentes pelas áreas.",
      expected_result: "Definição única de cálculo e painel mensal.",
      justification: "Base comparável para o comitê de pessoas.",
      process_description: "Cada área calcula o turnover de forma própria.",
      process_steps: "1. Coletar admissões e desligamentos\n2. Calcular por área\n3. Comparar",
      systems_used: "Folha, planilhas",
      execution_frequency: "Mensal",
      approximate_volume: "~200 eventos/mês",
      people_involved: 3,
      average_duration: "3 dias úteis",
      estimated_monthly_effort: 14,
      has_manual_controls: false,
      main_risks: "Definições divergentes entre áreas",
      client_impact: "Plano de retenção sem indicador confiável.",
      operational_impact: "Baixo",
      desired_deadline: "2026-11-05",
      perceived_criticality: "Baixa",
      category_id: 3,
      status_id: 3,
      priority_id: null,
      professional_id: null,
      screening_result: null,
      created_by: "juliana.almeida@empresa.com",
      created_at: "2026-08-20 09:10:00",
      updated_by: "joao.analyst@empresa.com",
      updated_at: "2026-08-26 15:00:00",
    },
    {
      request_id: 6,
      protocol: "MAAT-1W9V-8J4K",
      requester_id: "550e8400-e29b-41d4-a716-446655440006",
      requester_user_id: 101, // Analista Teste (perfil interno também pode solicitar)
      title: "Padronizar contratos de TI",
      request_type: "Padronização",
      process_name: "Contratação de fornecedores de TI",
      need_description: "Modelo padrão de contratos de serviço de TI.",
      problem_opportunity: "Contratos sem modelo, cláusulas despadronizadas.",
      expected_result: "Template único com cláusulas de SLA e segurança.",
      justification: "Reduz risco jurídico e tempo de elaboração.",
      process_description: "Cada contratação gera um contrato do zero.",
      process_steps: "1. Coletar demandas\n2. Redigir cláusulas\n3. Revisar com Jurídico",
      systems_used: "SharePoint, e-mail",
      execution_frequency: "Sob demanda",
      approximate_volume: "~8 contratos/ano",
      people_involved: 2,
      average_duration: "10 dias úteis",
      estimated_monthly_effort: 8,
      has_manual_controls: true,
      manual_controls_detail: "Tripla revisão Jurídico/TI/Compras.",
      main_risks: "Cláusulas omissas e responsabilidades mal definidas",
      client_impact: "Risco de passivos em auditoria de fornecedores.",
      operational_impact: "Médio",
      desired_deadline: "2026-12-01",
      perceived_criticality: "Média",
      category_id: 6,
      status_id: 4,
      priority_id: null,
      professional_id: null,
      screening_result: null,
      screening_justification: "Aguardando detalhamento do escopo técnico.",
      identified_risks: "Dependência da área jurídica para revisão.",
      next_steps: "Solicitante precisa confirmar tipos de cláusula.",
      created_by: "rafael.martins@empresa.com",
      created_at: "2026-08-12 11:30:00",
      updated_by: "joao.analyst@empresa.com",
      updated_at: "2026-08-28 16:45:00",
    },
    {
      request_id: 7,
      protocol: "MAAT-3Y8U-2D5G",
      requester_id: "550e8400-e29b-41d4-a716-446655440007",
      title: "Revisar fluxo de importação",
      request_type: "Revisão de processo",
      process_name: "Importação e nacionalização de cargas",
      need_description: "Diagnóstico do fluxo atual de importação.",
      problem_opportunity: "Etapas redundantes e atrasos na liberação aduaneira.",
      expected_result: "Fluxo redesenhado com responsáveis e prazos claros.",
      justification: "Importação representa 30% do custo logístico.",
      process_description: "Área opera com rotinas legadas e pouca padronização.",
      process_steps: "1. Levantar etapas\n2. Identificar gargalos\n3. Desenhar TO-BE",
      systems_used: "Siscomex, planilhas, e-mail",
      execution_frequency: "Contínua",
      approximate_volume: "~120 processos/mês",
      people_involved: 5,
      average_duration: "15 dias úteis",
      estimated_monthly_effort: 60,
      has_manual_controls: true,
      manual_controls_detail: "Checklist manual em cada desembaraço.",
      main_risks: "Multas por atraso e retenção de cargas",
      client_impact: "Desabastecimento de insumos importados.",
      operational_impact: "Crítico",
      desired_deadline: "2026-10-25",
      perceived_criticality: "Crítica",
      category_id: 7,
      status_id: 5,
      priority_id: null,
      preliminary_complexity: "alta",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440003",
      last_technical_message: "Mapeamento aprovado na triagem. Aguardando agenda.",
      created_by: "fernanda.souza@empresa.com",
      created_at: "2026-07-22 09:00:00",
      updated_by: "pedro.mapper@empresa.com",
      updated_at: "2026-08-05 10:30:00",
    },
    {
      request_id: 8,
      protocol: "MAAT-7H5R-9C2B",
      requester_id: "550e8400-e29b-41d4-a716-446655440008",
      title: "Viabilidade de e-commerce interno",
      request_type: "Estudo de viabilidade",
      process_name: "Venda entre filiais",
      need_description: "Avaliar viabilidade de um e-commerce interno.",
      problem_opportunity: "Excedentes de estoque não são aproveitados entre filiais.",
      expected_result: "Relatório de viabilidade com esforço, custo e ganho.",
      justification: "Possível redução de perdas e capital de giro.",
      process_description: "Filiais não possuem canal formal de troca de estoque.",
      process_steps: "1. Levantar estoques ociosos\n2. Modelar cenários\n3. Estimar ROI",
      systems_used: "ERP, planilhas",
      execution_frequency: "Única (estudo)",
      approximate_volume: "~1.500 SKUs ociosos",
      people_involved: 3,
      average_duration: "20 dias úteis",
      estimated_monthly_effort: 20,
      has_manual_controls: false,
      main_risks: "Subestimativa de esforço de integração",
      client_impact: "Filiais perdem vendas por falta de estoque.",
      operational_impact: "Médio",
      desired_deadline: "2026-11-15",
      perceived_criticality: "Baixa",
      category_id: 9,
      status_id: 6,
      priority_id: null,
      preliminary_complexity: "media",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440003",
      last_technical_message: "Reunião de levantamento agendada com a área.",
      estimated_completion: "2026-12-10",
      meeting_scheduled_for: "2026-09-20T14:00:00-03:00",
      meeting_link: "https://meet.empresa.com/viabilidade-eco",
      created_by: "gustavo.lima@empresa.com",
      created_at: "2026-07-25 13:00:00",
      updated_by: "pedro.mapper@empresa.com",
      updated_at: "2026-08-10 09:20:00",
    },
    {
      request_id: 9,
      protocol: "MAAT-4M6A-1S8T",
      requester_id: "550e8400-e29b-41d4-a716-446655440009",
      title: "Apoio à integração de NFe",
      request_type: "Apoio técnico",
      process_name: "Emissão e entrada de notas fiscais",
      need_description: "Suporte técnico na integração de notas com o ERP.",
      problem_opportunity: "Retrabalho manual no digitação de NFe de fornecedores.",
      expected_result: "Integração confiável eliminando digitação manual.",
      justification: "Reduz erros de lançamento e tempo de fechamento.",
      process_description: "NFe de fornecedores são digitados uma a uma.",
      process_steps: "1. Receber XML\n2. Validar dados\n3. Lançar no ERP",
      systems_used: "ERP, portal de fornecedores, XML",
      execution_frequency: "Diária",
      approximate_volume: "~300 NFe/dia",
      people_involved: 4,
      average_duration: "6 dias úteis",
      estimated_monthly_effort: 24,
      has_manual_controls: true,
      manual_controls_detail: "Conferência em lote ao fim do dia.",
      main_risks: "Lançamentos divergentes impactam impostos",
      client_impact: "Risco fiscal e multas em autuações.",
      operational_impact: "Alto",
      desired_deadline: "2026-10-30",
      perceived_criticality: "Alta",
      category_id: 8,
      status_id: 7,
      priority_id: null,
      preliminary_complexity: "media",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440001",
      last_technical_message: "Mapeamento em andamento com a equipe.",
      created_by: "camila.rodrigues@empresa.com",
      created_at: "2026-08-01 08:15:00",
      updated_by: "joao.analyst@empresa.com",
      updated_at: "2026-08-22 14:00:00",
    },
    {
      request_id: 10,
      protocol: "MAAT-8Q3J-5L7P",
      requester_id: "550e8400-e29b-41d4-a716-446655440010",
      title: "Central de dúvidas do SAC",
      request_type: "Outros",
      process_name: "Atendimento de dúvidas recorrentes",
      need_description: "Estruturar respostas para dúvidas recorrentes do SAC.",
      problem_opportunity: "40% dos chamados são dúvidas já respondidas.",
      expected_result: "Base de conhecimento com respostas padronizadas.",
      justification: "Reduz tempo de atendimento e aumenta autonomia do cliente.",
      process_description: "Atendentes respondem dúvidas repetidas individualmente.",
      process_steps: "1. Mapear dúvidas\n2. Redigir respostas\n3. Publicar na base",
      systems_used: "Central de atendimento, e-mail",
      execution_frequency: "Contínua",
      approximate_volume: "~1.200 chamados/mês",
      people_involved: 6,
      average_duration: "30 dias úteis",
      estimated_monthly_effort: 40,
      has_manual_controls: false,
      main_risks: "Conteúdo desatualizado após mudanças de regra",
      client_impact: "SLA de atendimento superior ao contrato.",
      operational_impact: "Médio",
      desired_deadline: "2026-11-10",
      perceived_criticality: "Média",
      category_id: 10,
      status_id: 8,
      priority_id: null,
      preliminary_complexity: "baixa",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440004",
      created_by: "roberto.nascimento@empresa.com",
      created_at: "2026-08-03 10:50:00",
      updated_by: "lucia.consult@empresa.com",
      updated_at: "2026-08-25 11:10:00",
    },
    {
      request_id: 11,
      protocol: "MAAT-2Z9E-6K4W",
      requester_id: "550e8400-e29b-41d4-a716-446655440011",
      title: "Automatizar entrada de notas",
      request_type: "Automação",
      process_name: "Entrada de notas fiscais de fornecedores",
      need_description: "Automação do lançamento de notas de entrada.",
      problem_opportunity: "Digitação manual com alto índice de erro.",
      expected_result: "Robô que valida e lança NFe no ERP.",
      justification: "Elimina retrabalho e libera 30h/mês da equipe.",
      process_description: "Assistentes digitam notas e conferem divergências.",
      process_steps: "1. Ler XML\n2. Conferir com pedido\n3. Lançar no ERP",
      systems_used: "ERP, portal fiscal",
      execution_frequency: "Diária",
      approximate_volume: "~250 NFe/dia",
      people_involved: 3,
      average_duration: "8 dias úteis",
      estimated_monthly_effort: 30,
      has_manual_controls: true,
      manual_controls_detail: "Conferência em lote ao fim do dia.",
      main_risks: "Divergência fiscal não tratada pelo robô",
      client_impact: "Multas por lançamento incorreto.",
      operational_impact: "Alto",
      desired_deadline: "2026-12-15",
      perceived_criticality: "Alta",
      category_id: 1,
      status_id: 9,
      priority_id: null,
      preliminary_complexity: "alta",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440005",
      last_technical_message: "Solicitação elegível. Aguardando priorização do comitê.",
      created_by: "patricia.castro@empresa.com",
      created_at: "2026-08-06 09:30:00",
      updated_by: "rafael.autler@empresa.com",
      updated_at: "2026-09-01 15:20:00",
    },
    {
      request_id: 12,
      protocol: "MAAT-6C4X-3N1Y",
      requester_id: "550e8400-e29b-41d4-a716-446655440012",
      title: "Dashboard do pipeline comercial",
      request_type: "Dashboard ou relatório",
      process_name: "Acompanhamento do funil de vendas",
      need_description: "Painel do pipeline por etapa, oportunidade e dono.",
      problem_opportunity: "Comitê comercial usa planilhas manuais semanais.",
      expected_result: "Dashboard atualizado diariamente com funil e projeção.",
      justification: "Aumenta confiabilidade da previsão de receita.",
      process_description: "Gestores consolidam funil em planilhas.",
      process_steps: "1. Extrair CRM\n2. Classificar etapas\n3. Montar painel",
      systems_used: "CRM, planilhas, Power BI",
      execution_frequency: "Semanal",
      approximate_volume: "~800 oportunidades ativas",
      people_involved: 4,
      average_duration: "10 dias úteis",
      estimated_monthly_effort: 25,
      has_manual_controls: false,
      main_risks: "Dados de CRM desatualizados",
      client_impact: "Previsão de receita com baixa acurácia.",
      operational_impact: "Médio",
      desired_deadline: "2026-11-30",
      perceived_criticality: "Média",
      category_id: 4,
      status_id: 9,
      priority_id: null,
      preliminary_complexity: "media",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440006",
      created_by: "diego.moreira@empresa.com",
      created_at: "2026-08-11 11:45:00",
      updated_by: "bianca.analyst@empresa.com",
      updated_at: "2026-09-02 09:15:00",
    },
    {
      request_id: 13,
      protocol: "MAAT-9V1F-7T5H",
      requester_id: "550e8400-e29b-41d4-a716-446655440013",
      title: "Análise de sazonalidade da produção",
      request_type: "Análise de dados",
      process_name: "Planejamento de capacidade",
      need_description: "Estudo de sazonalidade para dimensionar capacidade.",
      problem_opportunity: "Capacidade alta no ano e picos não previstos.",
      expected_result: "Modelo de sazonalidade por linha de produção.",
      justification: "Melhora planejamento de turnos e estoque.",
      process_description: "Planejamento baseado em intuição e histórico parcial.",
      process_steps: "1. Consolidar histórico\n2. Modelar sazonalidade\n3. Validar com área",
      systems_used: "ERP, planilhas, Python",
      execution_frequency: "Anual",
      approximate_volume: "~5 anos de histórico",
      people_involved: 2,
      average_duration: "15 dias úteis",
      estimated_monthly_effort: 20,
      has_manual_controls: false,
      main_risks: "Histórico incompleto em períodos de greve",
      client_impact: "Quebra de estoque em picos de demanda.",
      operational_impact: "Médio",
      desired_deadline: "2026-11-25",
      perceived_criticality: "Média",
      category_id: 5,
      status_id: 10,
      priority_id: null,
      preliminary_complexity: "alta",
      screening_result: "nao_elegivel",
      screening_justification: "Histórico insuficiente para modelo confiável.",
      identified_risks: "Dados incompletos entre 2023 e 2024.",
      professional_id: null,
      created_by: "larissa.teixeira@empresa.com",
      created_at: "2026-07-30 15:10:00",
      updated_by: "joao.analyst@empresa.com",
      updated_at: "2026-08-14 10:00:00",
    },
    {
      request_id: 14,
      protocol: "MAAT-3B8L-4W2S",
      requester_id: "550e8400-e29b-41d4-a716-446655440014",
      title: "Indicador de produção por linha",
      request_type: "Indicador",
      process_name: "Eficiência da produção (OEE)",
      need_description: "OEE consolidado por linha e turno.",
      problem_opportunity: "Métricas de OEE calculadas de forma dispersa.",
      expected_result: "Indicador oficial publicado no painel de fábrica.",
      justification: "Padroniza a leitura de eficiência entre turnos.",
      process_description: "Supervisores calculam OEE em planilhas locais.",
      process_steps: "1. Coletar eventos\n2. Calcular OEE\n3. Publicar no painel",
      systems_used: "MES, planilhas, Power BI",
      execution_frequency: "Diária",
      approximate_volume: "~10 linhas × 3 turnos",
      people_involved: 5,
      average_duration: "12 dias úteis",
      estimated_monthly_effort: 28,
      has_manual_controls: false,
      main_risks: "Falta de eventos consistentes no MES",
      client_impact: "Decisões de investimento em capacidade sem base.",
      operational_impact: "Alto",
      desired_deadline: "2026-12-05",
      perceived_criticality: "Alta",
      category_id: 3,
      status_id: 11,
      priority_id: 3,
      preliminary_complexity: "media",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440002",
      last_technical_message: "Priorizado pelo comitê de agosto.",
      estimated_completion: "2027-01-15",
      created_by: "henrique.barros@empresa.com",
      created_at: "2026-07-18 09:40:00",
      updated_by: "andre.mapper@empresa.com",
      updated_at: "2026-08-20 13:30:00",
    },
    {
      request_id: 15,
      protocol: "MAAT-7N2G-9X2Y",
      requester_id: "550e8400-e29b-41d4-a716-446655440015",
      title: "Padronizar inventário de tesouraria",
      request_type: "Melhoria de processo",
      process_name: "Inventário de contas a pagar",
      need_description: "Padronizar o inventário mensal de pagamentos.",
      problem_opportunity: "Listas divergentes entre tesouraria e contabilidade.",
      expected_result: "Inventário único reconciliado mensalmente.",
      justification: "Reduz diferenças e agiliza o fechamento.",
      process_description: "Equipes geram listas independentes a cada fechamento.",
      process_steps: "1. Extrair listas\n2. Conciliar\n3. Aprovar divergências",
      systems_used: "ERP, planilhas",
      execution_frequency: "Mensal",
      approximate_volume: "~3.000 títulos/mês",
      people_involved: 4,
      average_duration: "5 dias úteis",
      estimated_monthly_effort: 22,
      has_manual_controls: true,
      manual_controls_detail: "Assinatura dupla na conciliação.",
      main_risks: "Divergências ocultas até o fechamento anual",
      client_impact: "Fechamento contábil atrasado.",
      operational_impact: "Baixo",
      desired_deadline: "2026-11-12",
      perceived_criticality: "Baixa",
      category_id: 2,
      status_id: 12,
      priority_id: 2,
      preliminary_complexity: "baixa",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440008",
      last_technical_message: "Em backlog aguardando liberação de capacidade.",
      created_by: "vanessa.pinto@empresa.com",
      created_at: "2026-08-08 08:30:00",
      updated_by: "sofia.designer@empresa.com",
      updated_at: "2026-08-27 16:00:00",
    },
    {
      request_id: 16,
      protocol: "MAAT-5K8D-2M6C",
      requester_id: "550e8400-e29b-41d4-a716-446655440002",
      title: "RPA de faturamento",
      request_type: "Automação",
      process_name: "Emissão de faturas",
      need_description: "Automatizar emissão de faturas do comércio exterior.",
      problem_opportunity: "Faturas geradas manualmente com erros de 3%.",
      expected_result: "Robô que gera e valida faturas automaticamente.",
      justification: "Reduz erros e acelera o recebimento.",
      process_description: "Equipe gera faturas a partir de pedidos no ERP.",
      process_steps: "1. Coletar pedidos\n2. Gerar faturas\n3. Validar e enviar",
      systems_used: "ERP, sistema de câmbio",
      execution_frequency: "Diária",
      approximate_volume: "~80 faturas/dia",
      people_involved: 2,
      average_duration: "7 dias úteis",
      estimated_monthly_effort: 18,
      has_manual_controls: true,
      manual_controls_detail: "Dupla checagem da equipe comercial.",
      main_risks: "Fatura incorreta gera atraso de pagamento",
      client_impact: "Recebimento atrasado do cliente externo.",
      operational_impact: "Médio",
      desired_deadline: "2026-10-20",
      perceived_criticality: "Média",
      category_id: 1,
      status_id: 13,
      priority_id: null,
      preliminary_complexity: "media",
      screening_result: "nao_elegivel",
      screening_justification: "Encaminhada ao time de sistemas do câmbio.",
      identified_risks: "Responsabilidade sobre o sistema de câmbio é de outra área.",
      next_steps: "Follow-up com sistemas de câmbio.",
      professional_id: null,
      created_by: "carlos.oliveira@empresa.com",
      created_at: "2026-07-28 10:10:00",
      updated_by: "marina.dev@empresa.com",
      updated_at: "2026-08-12 09:50:00",
    },
    {
      request_id: 17,
      protocol: "MAAT-1P4A-8R3T",
      requester_id: "550e8400-e29b-41d4-a716-446655440006",
      title: "Padronizar onboarding de colaboradores",
      request_type: "Padronização",
      process_name: "Onboarding de novos colaboradores",
      need_description: "Padronizar o onboarding de TI para novos colaboradores.",
      problem_opportunity: "Acessos demoram e não seguem um checklist único.",
      expected_result: "Checklist padrão com prazos e responsáveis.",
      justification: "Reduz atraso de produtividade de novos colaboradores.",
      process_description: "Cada analista de TI faz onboarding de forma própria.",
      process_steps: "1. Criar checklist\n2. Providencionar acessos\n3. Validar com gestor",
      systems_used: "Active Directory, sistemas internos",
      execution_frequency: "Sob demanda",
      approximate_volume: "~30 onboards/mês",
      people_involved: 3,
      average_duration: "4 dias úteis",
      estimated_monthly_effort: 12,
      has_manual_controls: false,
      main_risks: "Acesso concedido sem autorização formal",
      client_impact: "Novos colaboradores sem acesso no 1º dia.",
      operational_impact: "Baixo",
      desired_deadline: "2026-10-28",
      perceived_criticality: "Baixa",
      category_id: 6,
      status_id: 14,
      priority_id: 1,
      preliminary_complexity: "baixa",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440002",
      last_technical_message: "Em desenvolvimento pela equipe de padronização.",
      estimated_completion: "2026-12-15",
      created_by: "rafael.martins@empresa.com",
      created_at: "2026-08-14 09:05:00",
      updated_by: "andre.mapper@empresa.com",
      updated_at: "2026-09-03 14:40:00",
    },
    {
      request_id: 18,
      protocol: "MAAT-4H6S-7E9W",
      requester_id: "550e8400-e29b-41d4-a716-446655440004",
      title: "Apoio técnico em banco de dados",
      request_type: "Apoio técnico",
      process_name: "Tuning de banco de dados do ERP",
      need_description: "Apoio técnico para otimização de queries do ERP.",
      problem_opportunity: "Relatórios críticos demoram mais de 10 minutos.",
      expected_result: "Queries otimizadas com tempo de resposta médio de 30s.",
      justification: "Libera horas da equipe e melhora o atendimento.",
      process_description: "Relatórios lentos travam o fechamento mensal.",
      process_steps: "1. Analisar planos de execução\n2. Otimizar índices\n3. Medir ganhos",
      systems_used: "ERP, PostgreSQL, ferramentas de tuning",
      execution_frequency: "Contínua",
      approximate_volume: "~40 relatórios lentos",
      people_involved: 2,
      average_duration: "18 dias úteis",
      estimated_monthly_effort: 25,
      has_manual_controls: false,
      main_risks: "Mudança impactar processos em produção",
      client_impact: "Usuários internos aguardando relatórios.",
      operational_impact: "Médio",
      desired_deadline: "2026-11-18",
      perceived_criticality: "Média",
      category_id: 8,
      status_id: 15,
      priority_id: 4,
      preliminary_complexity: "alta",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440007",
      last_technical_message: "Otimizações em homologação com a área.",
      estimated_completion: "2026-12-20",
      meeting_scheduled_for: "2026-10-05T15:00:00-03:00",
      created_by: "bruno.ferreira@empresa.com",
      created_at: "2026-07-15 14:30:00",
      updated_by: "thiago.dev@empresa.com",
      updated_at: "2026-09-04 10:25:00",
    },
    {
      request_id: 19,
      protocol: "MAAT-2M9Q-5Z1X",
      requester_id: "550e8400-e29b-41d4-a716-446655440007",
      title: "Dashboard de contratos",
      request_type: "Dashboard ou relatório",
      process_name: "Gestão de contratos jurídicos",
      need_description: "Painel com vigência e renovação de contratos.",
      problem_opportunity: "Contratos vencem sem aviso, gerando renovação automática.",
      expected_result: "Dashboard com alertas de vigência e renovações.",
      justification: "Evita renovações indevidas e multas.",
      process_description: "Contratos controlados em planilha pelo Jurídico.",
      process_steps: "1. Extrair contratos\n2. Classificar vigências\n3. Publicar alertas",
      systems_used: "SharePoint, planilhas",
      execution_frequency: "Mensal",
      approximate_volume: "~600 contratos ativos",
      people_involved: 2,
      average_duration: "8 dias úteis",
      estimated_monthly_effort: 16,
      has_manual_controls: true,
      manual_controls_detail: "Revisão jurídica mensal da planilha.",
      main_risks: "Renovação automática por descuido de vigência",
      client_impact: "Multas e custos desnecessários com fornecedores.",
      operational_impact: "Baixo",
      desired_deadline: "2026-10-22",
      perceived_criticality: "Baixa",
      category_id: 4,
      status_id: 16,
      priority_id: 3,
      preliminary_complexity: "baixa",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440008",
      last_technical_message: "Entregue e validado com a área jurídica.",
      estimated_completion: "2026-10-10",
      created_by: "fernanda.souza@empresa.com",
      created_at: "2026-07-10 11:00:00",
      updated_by: "sofia.designer@empresa.com",
      updated_at: "2026-10-11 09:00:00",
    },
    {
      request_id: 20,
      protocol: "MAAT-8T3F-6D4V",
      requester_id: "550e8400-e29b-41d4-a716-446655440009",
      title: "Viabilidade de CRM interno",
      request_type: "Estudo de viabilidade",
      process_name: "CRM de relacionamento interáreas",
      need_description: "Avaliar viabilidade de um CRM para equipes internas.",
      problem_opportunity: "Demandas interáreas não são registradas nem rastreadas.",
      expected_result: "Estudo de viabilidade com dimensão e custo.",
      justification: "Permite decisão de investimento estruturada.",
      process_description: "Demandas por e-mail com perda de histórico.",
      process_steps: "1. Levantar demandas\n2. Cotar ferramentas\n3. Estimar adoção",
      systems_used: "E-mail, planilhas, ferramentas de apoio",
      execution_frequency: "Única (estudo)",
      approximate_volume: "~200 demandas/mês",
      people_involved: 3,
      average_duration: "25 dias úteis",
      estimated_monthly_effort: 30,
      has_manual_controls: false,
      main_risks: "Baixa adesão das áreas internas",
      client_impact: "SLA interáreas sem controle consolidado.",
      operational_impact: "Baixo",
      desired_deadline: "2026-12-10",
      perceived_criticality: "Baixa",
      category_id: 9,
      status_id: 17,
      priority_id: null,
      preliminary_complexity: "media",
      screening_result: null,
      screening_justification: "Cancelada por decisão do comitê de direção.",
      professional_id: null,
      created_by: "camila.rodrigues@empresa.com",
      created_at: "2026-07-20 09:20:00",
      updated_by: "lucia.consult@empresa.com",
      updated_at: "2026-08-18 15:35:00",
    },
    {
      request_id: 21,
      protocol: "MAAT-5D7K-9N3W",
      requester_id: "550e8400-e29b-41d4-a716-446655440016",
      requester_user_id: 104,
      title: "Automatizar cotação de fornecedores",
      request_type: "Automação",
      process_name: "Processo de cotação de compras",
      need_description: "Cotações enviadas manualmente por e-mail para fornecedores.",
      problem_opportunity: "Comparação de propostas demora e não tem rastreabilidade.",
      expected_result: "Disparo e consolidação automática das cotações.",
      justification: "Reduz tempo de resposta e evita perda de propostas.",
      process_description: "Comprador já cria planilha e dispara e-mails um a um.",
      process_steps: "1. Montar lista\n2. Disparar e-mail\n3. Consolidar respostas",
      systems_used: "E-mail, planilhas",
      execution_frequency: "Semanal",
      approximate_volume: "~15 cotações/semana",
      people_involved: 2,
      average_duration: "3 dias úteis",
      estimated_monthly_effort: 10,
      has_manual_controls: false,
      main_risks: "Proposta perdida ou comparada fora do padrão",
      client_impact: "Compras mais lentas e sem histórico de fornecedores.",
      operational_impact: "Médio",
      desired_deadline: "2026-10-30",
      perceived_criticality: "Média",
      category_id: 1,
      status_id: 1,
      priority_id: null,
      professional_id: null,
      screening_result: null,
      created_by: "solicitante_teste@email.com",
      created_at: "2026-09-20 09:10:00",
      updated_by: null,
      updated_at: null,
    },
    {
      request_id: 22,
      protocol: "MAAT-3F8A-2C6M",
      requester_id: "550e8400-e29b-41d4-a716-446655440016",
      requester_user_id: 104,
      title: "Dashboard de gastos por centro de custo",
      request_type: "Dashboard ou relatório",
      process_name: "Acompanhamento de gastos por centro de custo",
      need_description: "Visão mensal dos gastos de Suprimentos por centro.",
      problem_opportunity: "Gastos consolidados manualmente em planilha.",
      expected_result: "Painel com evolução mensal e comparativo por filial.",
      justification: "Decisões de orçamento dependem do comparativo.",
      process_description: "Analista coleta extratos e monta o relatório no fim do mês.",
      process_steps: "1. Extrair gastos\n2. Consolidar por centro\n3. Distribuir relatório",
      systems_used: "ERP, planilhas",
      execution_frequency: "Mensal",
      approximate_volume: "~40 centros de custo",
      people_involved: 3,
      average_duration: "5 dias úteis",
      estimated_monthly_effort: 16,
      has_manual_controls: false,
      main_risks: "Centros sem classificação causam divergência",
      client_impact: "Orçamento aprovado com base em dados inconsistentes.",
      operational_impact: "Médio",
      desired_deadline: "2026-11-15",
      perceived_criticality: "Média",
      category_id: 4,
      status_id: 2,
      priority_id: null,
      professional_id: null,
      screening_result: null,
      created_by: "solicitante_teste@email.com",
      created_at: "2026-09-19 14:30:00",
      updated_by: "joao.analyst@empresa.com",
      updated_at: "2026-09-22 10:15:00",
    },
    {
      request_id: 23,
      protocol: "MAAT-7T2E-4W8R",
      requester_id: "550e8400-e29b-41d4-a716-446655440016",
      requester_user_id: 104,
      title: "Indicador de prazo de entrega de fornecedores",
      request_type: "Indicador",
      process_name: "Acompanhamento de OTIF de fornecedores",
      need_description: "Indicador de entregas no prazo por fornecedor.",
      problem_opportunity: "Prazo acompanhado em planilha sem padrão de cálculo.",
      expected_result: "OTIF calculado automaticamente por fornecedor.",
      justification: "Permite cobrança objetiva na homologação.",
      process_description: "Comprador registra atrasos manualmente.",
      process_steps: "1. Registrar entregas\n2. Calcular OTIF\n3. Reportar mensalmente",
      systems_used: "ERP, planilhas",
      execution_frequency: "Mensal",
      approximate_volume: "~300 entregas/mês",
      people_involved: 2,
      average_duration: "4 dias úteis",
      estimated_monthly_effort: 12,
      has_manual_controls: false,
      main_risks: "Critérios de cálculo divergentes entre filiais",
      client_impact: "Homologação de fornecedores sem indicador confiável.",
      operational_impact: "Médio",
      desired_deadline: "2026-11-30",
      perceived_criticality: "Média",
      category_id: 3,
      status_id: 3,
      priority_id: null,
      professional_id: null,
      screening_result: null,
      created_by: "solicitante_teste@email.com",
      created_at: "2026-09-18 11:00:00",
      updated_by: "joao.analyst@empresa.com",
      updated_at: "2026-09-22 16:40:00",
    },
    {
      request_id: 24,
      protocol: "MAAT-9X5V-3P1H",
      requester_id: "550e8400-e29b-41d4-a716-446655440016",
      requester_user_id: 104,
      title: "Análise da base de inadimplência por fornecedor",
      request_type: "Análise de dados",
      process_name: "Análise de inadimplência de fornecedores",
      need_description: "Base consolidada de inadimplência por fornecedor.",
      problem_opportunity: "Áreas divergem sobre os números de atraso.",
      expected_result: "Base analítica única com causa e valor por fornecedor.",
      justification: "Evita retrabalho entre compras e contas a pagar.",
      process_description: "Equipe cruza dados de ERP com planilhas manualmente.",
      process_steps: "1. Extrair base do ERP\n2. Cruzar com planilhas\n3. Validar divergências",
      systems_used: "ERP, planilhas",
      execution_frequency: "Mensal",
      approximate_volume: "~8.000 registros",
      people_involved: 3,
      average_duration: "5 dias úteis",
      estimated_monthly_effort: 20,
      has_manual_controls: false,
      main_risks: "Divergência de critério entre áreas",
      client_impact: "Decisões de crédito baseadas em dados inconsistentes.",
      operational_impact: "Alto",
      desired_deadline: "2026-11-20",
      perceived_criticality: "Alta",
      category_id: 5,
      status_id: 4,
      priority_id: null,
      professional_id: null,
      screening_result: null,
      created_by: "solicitante_teste@email.com",
      created_at: "2026-09-15 08:20:00",
      updated_by: "joao.analyst@empresa.com",
      updated_at: "2026-09-21 09:50:00",
    },
    {
      request_id: 25,
      protocol: "MAAT-6N4B-8J9Q",
      requester_id: "550e8400-e29b-41d4-a716-446655440016",
      requester_user_id: 104,
      title: "Padronizar cadastro de fornecedores",
      request_type: "Padronização",
      process_name: "Cadastro e onboarding de fornecedores",
      need_description: "Modelo padrão de dados e documentos no cadastro.",
      problem_opportunity: "Cadastros incompletos geram retrabalho em compras.",
      expected_result: "Checklist padrão de documentos e dados obrigatórios.",
      justification: "Reduz inconsistência e acelera homologação.",
      process_description: "Cada filial cadastra fornecedores de forma própria.",
      process_steps: "1. Definir campos\n2. Padronizar documentos\n3. Validar com filiais",
      systems_used: "ERP, SharePoint",
      execution_frequency: "Contínua",
      approximate_volume: "~90 fornecedores/ano",
      people_involved: 4,
      average_duration: "10 dias úteis",
      estimated_monthly_effort: 15,
      has_manual_controls: false,
      main_risks: "Filiais mantêm modelos locais após padronização",
      client_impact: "Homologação de fornecedores inconsistente.",
      operational_impact: "Médio",
      desired_deadline: "2026-12-01",
      perceived_criticality: "Média",
      category_id: 6,
      status_id: 5,
      priority_id: null,
      preliminary_complexity: "media",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440003",
      mapping_professional_id: "650e8400-e29b-41d4-a716-446655440003",
      last_technical_message: "Mapeamento aprovado na triagem. Aguardando agenda.",
      estimated_completion: "2026-11-30",
      meeting_scheduled_for: null,
      meeting_link: null,
      created_by: "solicitante_teste@email.com",
      created_at: "2026-09-12 10:45:00",
      updated_by: "pedro.mapper@empresa.com",
      updated_at: "2026-09-20 15:30:00",
    },
    {
      request_id: 26,
      protocol: "MAAT-2W8C-7Z5K",
      requester_id: "550e8400-e29b-41d4-a716-446655440016",
      requester_user_id: 104,
      title: "Apoio na integração de nota fiscal de entrada",
      request_type: "Apoio técnico",
      process_name: "Integração de nota fiscal de entrada",
      need_description: "Suporte técnico na integração de NFe de fornecedores.",
      problem_opportunity: "Retrabalho manual na digitação de NFe.",
      expected_result: "Integração confiável eliminando digitação manual.",
      justification: "Reduz erros de lançamento e tempo de fechamento.",
      process_description: "NFe de fornecedores são lançadas uma a uma.",
      process_steps: "1. Receber XML\n2. Validar dados\n3. Lançar no ERP",
      systems_used: "ERP, portal fiscal",
      execution_frequency: "Diária",
      approximate_volume: "~200 NFe/dia",
      people_involved: 3,
      average_duration: "8 dias úteis",
      estimated_monthly_effort: 24,
      has_manual_controls: false,
      main_risks: "Divergência fiscal impacta impostos",
      client_impact: "Fechamento contábil atrasado.",
      operational_impact: "Alto",
      desired_deadline: "2026-10-30",
      perceived_criticality: "Alta",
      category_id: 8,
      status_id: 6,
      priority_id: null,
      preliminary_complexity: "media",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440001",
      mapping_professional_id: "650e8400-e29b-41d4-a716-446655440001",
      last_technical_message: "Reunião de levantamento agendada com a área.",
      estimated_completion: "2026-10-30",
      meeting_scheduled_for: "2026-10-02T09:30:00-03:00",
      meeting_link: "https://meet.empresa.com/apoio-nfe-solicitante",
      created_by: "solicitante_teste@email.com",
      created_at: "2026-09-10 09:30:00",
      updated_by: "joao.analyst@empresa.com",
      updated_at: "2026-09-19 14:00:00",
    },
    {
      request_id: 27,
      protocol: "MAAT-4M9F-6T3B",
      requester_id: "550e8400-e29b-41d4-a716-446655440016",
      requester_user_id: 104,
      title: "Revisar fluxo de aprovação de compras",
      request_type: "Revisão de processo",
      process_name: "Fluxo de aprovação de compras",
      need_description: "Diagnóstico do fluxo atual de aprovação.",
      problem_opportunity: "Aprovações demoram por rotas despadronizadas.",
      expected_result: "Fluxo redesenhado com responsáveis e prazos.",
      justification: "Reduz tempo médio de aprovação.",
      process_description: "Cada comprador define a própria rota de aprovação.",
      process_steps: "1. Levantar etapas\n2. Identificar gargalos\n3. Desenhar TO-BE",
      systems_used: "E-mail, planilhas",
      execution_frequency: "Contínua",
      approximate_volume: "~250 solicitações/mês",
      people_involved: 5,
      average_duration: "12 dias úteis",
      estimated_monthly_effort: 30,
      has_manual_controls: true,
      manual_controls_detail: "Aprovação por e-mail sem trilha de auditoria.",
      main_risks: "Rotas divergentes geram retrabalho e atraso",
      client_impact: "Compras atrasadas por aprovações demoradas.",
      operational_impact: "Alto",
      desired_deadline: "2026-11-25",
      perceived_criticality: "Alta",
      category_id: 7,
      status_id: 7,
      priority_id: null,
      preliminary_complexity: "media",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440003",
      mapping_professional_id: "650e8400-e29b-41d4-a716-446655440003",
      last_technical_message: "Mapeamento em andamento com a equipe de compras.",
      created_by: "solicitante_teste@email.com",
      created_at: "2026-09-08 13:15:00",
      updated_by: "pedro.mapper@empresa.com",
      updated_at: "2026-09-18 11:20:00",
    },
    {
      request_id: 28,
      protocol: "MAAT-8Q6D-1R4N",
      requester_id: "550e8400-e29b-41d4-a716-446655440016",
      requester_user_id: 104,
      title: "Dashboard de estoque mínimo por filial",
      request_type: "Dashboard ou relatório",
      process_name: "Controle de estoque mínimo por filial",
      need_description: "Painel de estoque mínimo para suprimentos.",
      problem_opportunity: "Rupturas por falta de visão consolidada de estoque.",
      expected_result: "Dashboard com alertas de estoque abaixo do mínimo.",
      justification: "Evita rupturas e melhora planejamento de compras.",
      process_description: "Filial controla estoque em planilhas locais.",
      process_steps: "1. Extrair estoques\n2. Cruzar com mínimo\n3. Disparar alertas",
      systems_used: "ERP, planilhas, Power BI",
      execution_frequency: "Diária",
      approximate_volume: "~20 KBUs × 12 filiais",
      people_involved: 4,
      average_duration: "10 dias úteis",
      estimated_monthly_effort: 25,
      has_manual_controls: false,
      main_risks: "Estoque mínimo desatualizado por Kbu",
      client_impact: "Ruptura de insumo impacta a operação.",
      operational_impact: "Alto",
      desired_deadline: "2026-12-05",
      perceived_criticality: "Alta",
      category_id: 4,
      status_id: 11,
      priority_id: 3,
      preliminary_complexity: "media",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440002",
      mapping_professional_id: "650e8400-e29b-41d4-a716-446655440002",
      last_technical_message: "Solicitação priorizada com prioridade Alta no comitê de setembro.",
      estimated_completion: "2026-12-15",
      meeting_scheduled_for: null,
      meeting_link: null,
      created_by: "solicitante_teste@email.com",
      created_at: "2026-09-05 09:00:00",
      updated_by: "bianca.analyst@empresa.com",
      updated_at: "2026-09-17 10:30:00",
    },
    {
      request_id: 29,
      protocol: "MAAT-1L7G-5P9A",
      requester_id: "550e8400-e29b-41d4-a716-446655440016",
      requester_user_id: 104,
      title: "Dashboard de fechamento de compras",
      request_type: "Dashboard ou relatório",
      process_name: "Fechamento mensal de compras",
      need_description: "Painel consolidado do fechamento mensal de compras.",
      problem_opportunity: "Fechamento depende de consolidação manual.",
      expected_result: "Dashboard automático com pedidos, nota e pagamentos.",
      justification: "Agiliza o fechamento e reduz divergências.",
      process_description: "Equipe consolida pedidos e notas no fim do mês.",
      process_steps: "1. Extrair pedidos\n2. Conciliar notas\n3. Publicar painel",
      systems_used: "ERP, planilhas, Power BI",
      execution_frequency: "Mensal",
      approximate_volume: "~1.500 pedidos/mês",
      people_involved: 4,
      average_duration: "10 dias úteis",
      estimated_monthly_effort: 28,
      has_manual_controls: true,
      manual_controls_detail: "Conferência dupla no fechamento.",
      main_risks: "Notas sem pedido geram divergência no fechamento",
      client_impact: "Fechamento contábil atrasado.",
      operational_impact: "Alto",
      desired_deadline: "2026-09-19",
      perceived_criticality: "Alta",
      category_id: 4,
      status_id: 16,
      priority_id: 2,
      preliminary_complexity: "media",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440002",
      mapping_professional_id: "650e8400-e29b-41d4-a716-446655440002",
      last_technical_message: "Entregue e validado com a área de compras.",
      estimated_completion: "2026-09-19",
      created_by: "solicitante_teste@email.com",
      created_at: "2026-08-18 09:40:00",
      updated_by: "sofia.designer@empresa.com",
      updated_at: "2026-09-21 18:00:00",
    },
    {
      request_id: 30,
      protocol: "MAAT-3H8Z-9S2N",
      requester_id: "550e8400-e29b-41d4-a716-446655440016",
      requester_user_id: 104,
      title: "Viabilidade de integração com portal de fornecedores",
      request_type: "Estudo de viabilidade",
      process_name: "Integração com portal de fornecedores",
      need_description: "Avaliar viabilidade de integração com o portal.",
      problem_opportunity: "Portal proprietário com API restrita.",
      expected_result: "Relatório de viabilidade com esforço e custo.",
      justification: "Decisão de investimento em integração.",
      process_description: "Acessos e dados do portal operados manualmente.",
      process_steps: "1. Avaliar API\n2. Cotar integração\n3. Estimar ROI",
      systems_used: "Portal de fornecedores, ERP",
      execution_frequency: "Única (estudo)",
      approximate_volume: "~1 fonte externa",
      people_involved: 2,
      average_duration: "15 dias úteis",
      estimated_monthly_effort: 15,
      has_manual_controls: false,
      main_risks: "Fornecedor sem contrato de integração",
      client_impact: "Manualidade mantida no acesso ao portal.",
      operational_impact: "Baixo",
      desired_deadline: "2026-11-10",
      perceived_criticality: "Baixa",
      category_id: 9,
      status_id: 10,
      priority_id: null,
      preliminary_complexity: "alta",
      screening_result: "nao_elegivel",
      screening_justification: "API restrita e custo de licença inviável.",
      identified_risks: "Dependência de fornecedor externo sem contrato.",
      next_steps: "Reavaliar em trimestre seguinte com orçamento de integração.",
      professional_id: null,
      created_by: "solicitante_teste@email.com",
      created_at: "2026-09-03 15:20:00",
      updated_by: "joao.analyst@empresa.com",
      updated_at: "2026-09-15 09:00:00",
    },
  ]);

  await knex.raw(
    "SELECT setval('requests_request_seq', (SELECT COALESCE(MAX(request_id), 1) FROM requests))",
  );
}
