export async function seed(knex) {
  await knex("requests").insert([
    {
      request_id: "aa000000-0000-4000-8000-000000000001",
      protocol: "MAAT-2026-000001",
      requester_id: "550e8400-e29b-41d4-a716-446655440001",
      process_name: "Conciliação bancária mensal",
      title: "Automatizar conciliação bancária",
      need_description: "Processo manual com alta carga operacional hoje.",
      problem_opportunity: "Conciliação manual sujeita a erros e consumo de 40h/mês.",
      expected_result: "Conciliação automatizada com conferência eletrônica.",
      current_process_description:
        "Equipe baixa extratos, concilia em planilha e confere item a item.",
      systems_used: "ERP, portal bancário, planilhas Excel",
      execution_frequency: "Mensal",
      approximate_volume: "~5.000 lançamentos por mês",
      people_involved: 3,
      average_duration: "5 dias úteis",
      estimated_monthly_effort: "40 horas/mês",
      has_manual_controls: true,
      main_risks: "Divergência sem identificação, retrabalho em fechamento",
      operational_impact: "Atualmente gastam-se 40h/mês nesta atividade.",
      client_impact: 5,
      desired_deadline: "2026-09-30",
      perceived_criticality: "alta",
      has_documentation: false,
      has_restricted_info: true,
      category_id: 1,
      status_id: 5,
      priority_id: 3,
      preliminary_complexity: "media",
      screening_result: "elegivel",
      professional_id: "650e8400-e29b-41d4-a716-446655440001",
      created_by: "maria.silva@empresa.com",
      created_at: "2026-07-01 09:00:00",
      updated_by: "joao.analyst@empresa.com",
      updated_at: "2026-07-08 12:00:00",
      is_restricted_info: true,
    },
    {
      request_id: "aa000000-0000-4000-8000-000000000002",
      protocol: "MAAT-2026-000002",
      requester_id: "550e8400-e29b-41d4-a716-446655440002",
      process_name: "Relatório de vendas",
      title: "Criar dashboard de vendas",
      need_description: "Necessidade de visão unificada das vendas por região.",
      problem_opportunity: "Dados espalhados em planilhas sem padrão.",
      expected_result: "Dashboard com indicadores de venda em tempo real.",
      systems_used: "CRM, planilhas, BI atual",
      execution_frequency: "Semanal",
      approximate_volume: "6 planilhas por semana",
      people_involved: 2,
      estimated_monthly_effort: "16 horas/mês",
      operational_impact: "Decisões dependem de compilação manual.",
      client_impact: 3,
      desired_deadline: "2026-10-15",
      perceived_criticality: "media",
      category_id: 2,
      status_id: 9,
      professional_id: "650e8400-e29b-41d4-a716-446655440003",
      screening_result: "elegivel",
      created_by: "carlos.oliveira@empresa.com",
      created_at: "2026-07-02 10:30:00",
      updated_by: "pedro.mapper@empresa.com",
      updated_at: "2026-07-18 11:00:00",
    },
  ]);
}
